POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "abc",
    "password": "abc"
}

###

DELETE http://localhost:3001/users

###

DELETE http://localhost:3001/rooms

###

POST http://localhost:3001/rooms
Content-Type: application/json

{
    "roomName": "Global"
}

###
DELETE http://localhost:3001/rooms/Test1-abc

###
GET http://localhost:3001/roomsList

###
GET http://localhost:3001/users

###

GET https://chat-app-server-red-seven.vercel.app/users